### ISSUE TITLE
Keep tmp dir for none production context

### ISSUE THREAD

**Issue by MugeSo** [bearsunday/BEAR.AppMeta#10]
I request to keep tmp dir over requests for none production context such as testing.
Currently it will be removed.

For example, 
temporary directory can be kept on end-to-end testing.
And keeping it makes faster test execution.

**Comment by koriym** [comment]
I found the people are confused easily in the suggested way (keep tmp/_). Also they asked to me to remove compiled files under var/tmp/_. It seems they can feel more confident with deletion each time.

But I know what you mean, and I did so in beginning.
Maybe we need more smart way not only "do or don't." ?

**Comment by MugeSo** [comment]
> Maybe we need more smart way not only "do or don't." ?

I think so too.
How about add 3rd parameter of constructor or more context keyword for keep tmp/

``` php
$isNotKeepTmp = strpos($context, 'keep-tmp') === false; // new keyword keep-tmp
if ($isNotProd) {
    if ($isNotKeepTmp) $this->initForDevelop($this->tmpDir);
    ini_set('error_log', $this->logDir . "/app.{$context}.log");
}
```

**Comment by koriym** [comment]
That is possible, but I prefer "no-if" design when it's possible.

**Comment by koriym** [comment]
How about using `Bootstrap::getAppInstance()` ?

This is original script to get $app;

``` php
$app = (new Bootstrap)->getApp(__NAMESPACE__, $context);
```

I provide `getAppInstance()` method for user's original AppMeta.

``` php
$myAppMeta = new MyAppMeta;
$app = (new Bootstrap)->getAppInstance($myAppMeta, $context);
```

Your `MyAppMeta` is like this.

``` php
class MyAppMeta extends AbstractAppMeta
{
    /**
     * @param string $context
     */
    public function __construct($context = 'app')
    {
        $this->name = 'YOUR-APP-NAME';
        $this->appDir = dirname(__DIR__);
        $this->tmpDir = $this->appDir . '/var/tmp/'. $context;
        $this->logDir = $this->appDir . '/var/log';
    }
}
```

You can define your own initialization / setup here as well.

**Comment by koriym** [comment]
#11
